# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "shanghai"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.25"
  src = "src"
  test = "test"

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  # blockscout type scanners do not need a key
  flow = { key = "", url = "${FLOW_SCAN_URL}", chain = 747 }
  flow_test = { key = "", url = "${FLOW_TEST_SCAN_URL}", chain = 545 }
  mantle = { key = "", url = "${MANTLE_SCAN_URL}", chain = 5000 }
  mantle_sepolia = { key = "", url = "${MANTLE_SEPOLIA_SCAN_URL}", chain = 5003 }
  scroll = { key = "${SCROLL_SCAN_KEY}", chain = 534352 }
  scroll_sepolia = { key = "${SCROLL_SCAN_KEY}", chain = 534351 }
  base = { key = "${BASE_SCAN_KEY}", chain = 8453 }
  base_sepolia = { key = "${BASE_SCAN_KEY}", chain = 84532 }
  polygon = { key = "${POLYGON_SCAN_KEY}", chain = 137 }
  polygon_amoy = { key = "${POLYGON_SCAN_KEY}", chain = 80002 }
  zircuit = { key = "${ZIRCUIT_SCAN_KEY}", chain = 48900, url = "${ZIRCUIT_SCAN_URL}" }
  zircuit_test = { key = "${ZIRCUIT_TEST_SCAN_KEY}", chain = 48899, url = "${ZIRCUIT_TEST_SCAN_URL}" }
  morph = { key = "", chain = 2818, url = "${MORPH_SCAN_URL}" }
  morph_test = { key = "", chain = 2810, url = "${MORPH_TEST_SCAN_URL}" }
  bitkub = { key = "", chain = 96, url = "${BITKUB_SCAN_URL}" }
  bitkub_test = { key = "", chain = 25925, url = "${BITKUB_TEST_SCAN_URL}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  flow = "${FLOW_RPC_URL}"
  flow_test = "${FLOW_TEST_RPC_URL}"
  mantle = "${MANTLE_RPC_URL}"
  mantle_sepolia = "${MANTLE_SEPOLIA_RPC_URL}"
  scroll = "${SCROLL_RPC_URL}"
  scroll_sepolia = "${SCROLL_SEPOLIA_RPC_URL}"
  base = "${BASE_RPC_URL}"
  base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
  polygon = "${POLYGON_RPC_URL}"
  polygon_amoy = "${POLYGON_AMOY_RPC_URL}"
  zircuit = "${ZIRCUIT_RPC_URL}"
  zircuit_test = "${ZIRCUIT_TEST_RPC_URL}"
  morph = "${MORPH_RPC_URL}"
  morph_test = "${MORPH_TEST_RPC_URL}"
  bitkub = "${BITKUB_RPC_URL}"
  bitkub_test = "${BITKUB_TEST_RPC_URL}"
