import { Inter } from "next/font/google";
import "./globals.css";
import { DynamicContextProvider } from "@dynamic-labs/sdk-react-core";
import { EthereumWalletConnectors } from "@dynamic-labs/ethereum";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Setting up list of evmNetworks
const evmNetworks = [
  {
    blockExplorerUrls: ["https://sepolia.base.etherscan.io/"],
    chainId: 84532,
    chainName: "Base Sepolia",
    iconUrls: ["https://app.dynamic.xyz/assets/networks/eth.svg"],
    name: "Base",
    nativeCurrency: {
      decimals: 18,
      name: "Ether",
      symbol: "ETH",
      iconUrl: "https://app.dynamic.xyz/assets/networks/eth.svg",
    },
    networkId: 84532,

    rpcUrls: [
      "https://lb.drpc.org/ogrpc?network=base-sepolia&dkey=AohqDtY2d0mWl_Jj_v7okBj4v538o_IR76cRFhW5UfFk",
    ],
    vanityName: "ETH ",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicContextProvider
          settings={{
            environmentId: "f3bb6442-8dbf-4692-9d5d-1644bc63086c",
            walletConnectors: [EthereumWalletConnectors],
            overrides: { evmNetworks },
          }}
        >
          <div className="mx-[10%]">{children}</div>
        </DynamicContextProvider>
      </body>
    </html>
  );
}
