import { Inter } from "next/font/google";
import "./globals.css";
import { DynamicContextProvider } from "@dynamic-labs/sdk-react-core";
import { EthereumWalletConnectors } from "@dynamic-labs/ethereum";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicContextProvider
          settings={{
            environmentId: "f3bb6442-8dbf-4692-9d5d-1644bc63086c",
            walletConnectors: [EthereumWalletConnectors],
          }}
        >
          <div className="mx-[10%]">{children}</div>
        </DynamicContextProvider>
      </body>
    </html>
  );
}
